# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  catalog.api:
    build:
      context: "C:\\Projects\\ozkaya\\Shopping\\src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\tayfu\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\ozkaya\\Shopping\\src\\Services\\Catalog\\Catalog.API:/app:rw"
    - "C:\\Projects\\ozkaya\\Shopping\\src:/src:rw"
    working_dir: "/app"
