# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "C:\\Projects\\ozkaya\\Shopping\\src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "basketapi:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "C:\\Users\\tayfu\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\ozkaya\\Shopping\\src\\Services\\Basket\\Basket.API:/app:rw"
    - "C:\\Projects\\ozkaya\\Shopping\\src:/src:rw"
    - "C:\\Users\\tayfu\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.4\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\tayfu\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_3_17_14_22_01:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "C:\\Projects\\ozkaya\\Shopping\\src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "catalogapi:dev"
    ports:
    - "127.0.0.1:57001:57100"
    - "127.0.0.1:57201:57300"
    volumes:
    - "C:\\Users\\tayfu\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\ozkaya\\Shopping\\src\\Services\\Catalog\\Catalog.API:/app:rw"
    - "C:\\Projects\\ozkaya\\Shopping\\src:/src:rw"
    - "C:\\Users\\tayfu\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.4\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\tayfu\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_3_17_14_22_01:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "C:\\Projects\\ozkaya\\Shopping\\src"
      dockerfile: "Services/Discount/Discount.Grpc/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "discountgrpc:dev"
    ports:
    - "127.0.0.1:57002:57100"
    - "127.0.0.1:57202:57300"
    volumes:
    - "C:\\Users\\tayfu\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\ozkaya\\Shopping\\src\\Services\\Discount\\Discount.Grpc:/app:rw"
    - "C:\\Projects\\ozkaya\\Shopping\\src:/src:rw"
    - "C:\\Users\\tayfu\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.4\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\tayfu\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_3_17_14_22_01:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  ordering.api:
    build:
      context: "C:\\Projects\\ozkaya\\Shopping\\src"
      dockerfile: "Services/Ordering/Ordering.API/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/dotnet/dotnet"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "orderingapi:dev"
    ports:
    - "127.0.0.1:57003:57100"
    - "127.0.0.1:57203:57300"
    volumes:
    - "C:\\Users\\tayfu\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\ozkaya\\Shopping\\src\\Services\\Ordering\\Ordering.API:/app:rw"
    - "C:\\Projects\\ozkaya\\Shopping\\src:/src:rw"
    - "C:\\Users\\tayfu\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.3.4\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.3.4\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\tayfu\\AppData\\Local\\JetBrains\\Rider2023.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_3_17_14_22_01:/var/opt/rider-debugger:rw"
    working_dir: "/app"
