# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  basket.api:
    build:
      context: "C:\\Projects\\ozkaya\\Shopping\\src"
      dockerfile: "Services/Basket/Basket.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Basket.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "basketapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\tayfu\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\ozkaya\\Shopping\\src\\Services\\Basket\\Basket.API:/app:rw"
    - "C:\\Projects\\ozkaya\\Shopping\\src:/src:rw"
    working_dir: "/app"
  catalog.api:
    build:
      context: "C:\\Projects\\ozkaya\\Shopping\\src"
      dockerfile: "Services/Catalog/Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalogapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\tayfu\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\ozkaya\\Shopping\\src\\Services\\Catalog\\Catalog.API:/app:rw"
    - "C:\\Projects\\ozkaya\\Shopping\\src:/src:rw"
    working_dir: "/app"
  discount.grpc:
    build:
      context: "C:\\Projects\\ozkaya\\Shopping\\src"
      dockerfile: "Services/Discount/Discount.Grpc/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Discount.Grpc.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "discountgrpc:dev"
    ports: []
    volumes:
    - "C:\\Users\\tayfu\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\ozkaya\\Shopping\\src\\Services\\Discount\\Discount.Grpc:/app:rw"
    - "C:\\Projects\\ozkaya\\Shopping\\src:/src:rw"
    working_dir: "/app"
  ordering.api:
    build:
      context: "C:\\Projects\\ozkaya\\Shopping\\src"
      dockerfile: "Services/Ordering/Ordering.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Ordering.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "orderingapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\tayfu\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\ozkaya\\Shopping\\src\\Services\\Ordering\\Ordering.API:/app:rw"
    - "C:\\Projects\\ozkaya\\Shopping\\src:/src:rw"
    working_dir: "/app"
  yarpapigateway:
    build:
      context: "C:\\Projects\\ozkaya\\Shopping\\src"
      dockerfile: "ApiGateways/YarpApiGateway/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/YarpApiGateway.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "yarpapigateway:dev"
    ports: []
    volumes:
    - "C:\\Users\\tayfu\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Projects\\ozkaya\\Shopping\\src\\ApiGateways\\YarpApiGateway:/app:rw"
    - "C:\\Projects\\ozkaya\\Shopping\\src:/src:rw"
    working_dir: "/app"
